$color0 = rgba(05050eff)
$color1 = rgba(8998afff)
$color2 = rgba(98a5b9ff)
$color3 = rgba(94acccff)
$color4 = rgba(abb7cbff)
$color5 = rgba(c3bdc9ff)
$color6 = rgba(b8c5daff)
$color7 = rgba(dee2eaff)
$color8 = rgba(9b9ea3ff)
$color9 = rgba(8998afff)
$color10 = rgba(98a5b9ff)
$color11 = rgba(94acccff)
$color12 = rgba(abb7cbff)
$color13 = rgba(c3bdc9ff)
$color14 = rgba(b8c5daff)
$color15 = rgba(dee2eaff)
