source = ~/.config/hypr/colors.conf

# Background
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 4
    blur_size = 3
    vibrancy = 0.19
}

# clock
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo "<span><b>$(date +"%I:%M")</b></span>"
    color = $color5
    font_size = 85
    font_family = Google Sans Medium
    position = 140, 175
    halign = left
    valign = center
}

# day and month and years
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $color7
    font_size = 15
    font_family = Google Sans
    position = 150, 95
    halign = left
    valign = center
}

# Label Essential Moment
label {
    monitor = HDMI-A-1
    text = Hi, $USER • $LAYOUT
    text_align = center # center/right or any value for default left. multi-line text alignment inside label container
    color = $color7
    font_size = 15
    font_family = Google Sans
    rotate = 0 # degrees, counter-clockwise

    position = 150, 65
    halign = left
    valign = center
}

# Input Text Here
input-field {
    monitor = HDMI-A-1
    size = 250, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.3 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.13)
    font_color = $color7
    check_color = rgba(0, 200, 0, 0.23)
    fail_color = rgba(255, 0, 0, 0.16)
    fade_on_empty = false
    font_family = Google Sans
    placeholder_text = <i>enter pass here, sweetheart...</i>
    hide_input = false
    position = 150, -10
    halign = left
    valign = center
}